language: java
sudo: false
os: mac
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx512m"
    - JAVA_OPTS="-XX:MaxPermSize=256m -Xmx512m"
jdk:
  - oraclejdk7
  - openjdk7
before_script:
  - cd download-maven-plugin
script:
  - mvn clean install --batch-mode --errors
  - mvn verify -Pits --batch-mode --errors
