 os:
    - osx
    
language: java

env:
  global:
    - secure: "HZ7J4B0hSDB2H6ljNXYp7LKgFAA3TUFF22qlSVBiI8Qb3dChwM6t/sNVhQnMKfTREOinpvLOt9rDwHBz1ysPtP+r0iqQyDo5GQDTyTXkFskQFO4myelOamZguJQu+bNTQgKHoF1vbFTysC5mpcInYhcu5veLkgH1PRgNFQcqles="
    - secure: "CVY1NoFW3e3Hfvgvu2mMC4vaQdmPmyHvuFzqqGlpdH3fdMdqG1xzHi+oXv0gK3tbxB0JNfXXvIiNXpGZ06nGcvQYGIRdRU3armJ3P3zv8KXrhitiv1HS08K4pMzgv9+uVwTdxgC0np5tVWQDvV2MSd424ykZrvR07tm2JWxIybU="
  matrix:
    - CUSTOM_JDK="default"
    - CUSTOM_JDK="oraclejdk8"
    - CUSTOM_JDK="oraclejdk7"
    - CUSTOM_JDK="openjdk7"

matrix:
  exclude:
     # On OSX, run with default JDK only.
     - os: osx
       env: CUSTOM_JDK="oraclejdk8"
     - os: osx
       env: CUSTOM_JDK="oraclejdk7"
     - os: osx
       env: CUSTOM_JDK="openjdk7"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi

script: 
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then mvn install -P osx64; fi
