language: java

notifications:
  email: false
  
  sudo: false
  
jdk:
  - oraclejdk8
#  - openjdk7
#  - openjdk6
before_install:
  - mvn install -Dmaven.javadoc.skip=true
   - "echo skipped"
install:
  - "echo skipped"
script:
#  - "echo skipped" 
  - mvn install -Dmaven.javadoc.skip=true
# - mvn deploy
